[versions]
# Plugins
kotlin = "2.3.10"
dokka = "2.1.0"
kotlinter = "5.4.2"
pluginYml = "0.6.0"
minecraftServer = "4.0.2"
shadow = "8.1.1"
mavenPublish = "0.35.0"

# Libraries
spigot8 = "1.8.8-R0.1-SNAPSHOT"
spigotLatest = "1.21.4-R0.1-SNAPSHOT"
paper = "1.16.5-R0.1-SNAPSHOT"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
dokka-javadoc = { id = "org.jetbrains.dokka-javadoc", version.ref = "dokka" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
pluginYml-bukkit = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "pluginYml" }
minecraftServer = { id = "dev.s7a.gradle.minecraft.server", version.ref = "minecraftServer" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }

[libraries]
spigot8 = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot8" }
spigotLatest = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigotLatest" }
paper = { group = "com.destroystokyo.paper", name = "paper-api", version.ref = "paper" }
